# JVM del daemon de Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX (obligatorio para appcompat/core-ktx)
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Builds no transitivos de R (mas rapido)
android.nonTransitiveRClass=true

# Paralelismo y cache de configuracion
org.gradle.parallel=true
org.gradle.caching=true
